dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: imagenet
net: resnet50
adapter: bottleneck_adapter
mode: from_scratch
#mode: full_tuning
#mode: linear_probing
#mode: adapter
optimizer: sgd
attacker: black_box
weight: pretrain

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 8

num_epochs: 90
warmup_steps: 500
batch_size: 1024
lr: 0.4
momentum: 0.9
wd: 1e-4

dp: False
augment: True
sigma: 1.5
c: 10
delta: 1e-5
