dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights
rpath_ckpt: ckpt_ylzou/places365_resnet18_from_scratch_sgd_epoch80_bs1024_lr0.4_gpu8/last.ckpt

dataset: imagenet
net: resnet18
#mode: from_scratch
#mode: full_tuning
#mode: linear_probing
#mode: adapter
mode: sparse_tuning
optimizer: sgd
attacker: black_box
weight: ckpt

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 8

num_epochs: 70
warmup_steps: 615
batch_size:
  train: 65536
  val: 512
  test: 512
max_batch_size: 256
lr: 7.68
momentum: 0.9
wd: 1e-4

dp: True
augment: False
c: 1
epsilon: 10
delta: 1e-6
