dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: imagenet
net: resnet
adapter: bottleneck_adapter
mode: from_scratch
#mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: sgd
attacker: black_box

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 8

# 100 for 'from_scratch', 50 for others
num_epochs: 90
warmup_steps: 100
batch_size: 1024
# lr setting:
# non-dp: 1e-2 for 'fine_tuning' and 'linear_probing', 3e-2 for 'from_scratch' and 'adapter'
# dp: 1e-4 for 'fine_tuning', 3e-4 for 'linear_probing' and 'adapter', 1e-3 for 'from_scratch'
lr: 0.4
momentum: 0.9
wd: 1e-4

dp: False
augment: True
sigma: 1.5
c: 10
delta: 1e-5
