dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights
rpath_ckpt: ckpt/places365_vit_0.51978.ckpt

dataset: imagenet
net: vit
adapter: mlp_adapter
#mode: from_scratch
#mode: full_tuning
#mode: linear_probing
#mode: adapter
mode: sparse_tuning
optimizer: adamw
attacker: black_box
weight: ckpt

gpus: [0,1,2,3,4,5,6,7]
num_workers: 8

num_epochs: 90
warmup_steps: 500
batch_size:
  train: 1024
  val: 512
  test: 512
max_batch_size: 512
# lr setting
# dp: 1e-4 for 'full_tuning', 5e-4 for 'adapter'
lr: 5e-4
momentum: 0.9
wd: 0

dp: True
augment: False
#sigma: 1.5
c: 1
epsilon: 10
delta: 1e-6
