dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: chexpert
uncertainty: u_zeros  # u_zeros or u_ones
net: convnext
#adapter: mlp_adapter
mode: from_scratch
#mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: adamw

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 4

num_epochs: 10
warmup_steps: 500
batch_size: 1024
# 256 for adapter
max_batch_size: 64
#batch_size: 16
#max_batch_size: 512
# lr setting
# dp: 3e-3 for 'adapter' and 'from_scratch'
lr: 3e-3
momentum: 0.9
wd: 0.0

dp: True
augment: False
#sigma: 1.5
c: 1
epsilon: 8
delta: 1e-5
