dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: chexpert
uncertainty: u_zeros  # u_zeros or u_ones
net: resnet
adapter: bottleneck_adapter
#mode: from_scratch
mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: adamw

gpus: [0, 1]
num_workers: 4

num_epochs: 18
warmup_steps: 500
batch_size: 16
#max_batch_size: 512
lr:
  sgd: 1e-4
  adamw: 3e-5
  sgd_dp: 1e-4
  adamw_dp: 3e-5
momentum: 0.9
wd:
  sgd: 1e-4
  adamw: 1e-2

dp: False
augment: False
#sigma: 1.5
c: 10
epsilon: 5
delta: 1e-5
