dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: chexpert
net: vit
adapter: mlp_adapter
mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: sgd

gpus: [0, 1]
num_workers: 8

num_epochs: 100
warmup_steps: 500
batch_size: 512
#max_batch_size: 512
lr: 1e-2
momentum: 0.9
wd: 1e-4

dp: True
augment: False
#sigma: 1.5
c: 10
epsilon: 5
delta: 1e-5