dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar10
net: convnext
adapter: mlp_adapter
#mode: from_scratch
#mode: fine_tuning
#mode: linear_probing
mode: adapter
optimizer: adamw

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 4


num_epochs: 10
warmup_steps: 500
batch_size: 1024
max_batch_size: 256
# 1e-3 for 'adapter'
lr: 1e-3
momentum: 0.9
wd: 0.0

dp: True
augment: False
#sigma: 1.5
#c: 10
c: 1
epsilon: 8
delta: 1e-5
#ratio_public: 1.0
