dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

net: dpsgd_net
dataset: cifar10

gpus: [0, 1]
num_workers: 3

num_epochs: 500
batch_size: 512
lr: 0.1
momentum: 0.9
wd: 1e-4

dp: True
augment: True
sigma: 1.5
c: 10
delta: 1e-5