dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar100
net: vit
adapter: mlp_adapter
#mode: fine_tuning
mode: linear_probing
#mode: adapter

gpus: [0, 1]
num_workers: 4

num_epochs: 100
warmup_steps: 500
batch_size: 512
lr: 1e-3
momentum: 0.9
wd: 0

dp: True
augment: False
sigma: 1.5
c: 10
delta: 1e-5