dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar10
net: convnext
adapter: mlp_adapter
mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: adamw

gpus: [0]
num_workers: 4

num_epochs: 10
warmup_steps: 0
batch_size: 64
lr:
  sgd: 3e-3
  adamw: 4e-4
  sgd_dp: 3e-3
  adamw_dp: 3e-4
momentum: 0.9
wd:
  sgd: 1e-4
  adamw: 0.05

dp: False
augment: True
sigma: 0.01
c: 10
delta: 1e-5
