dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar100
net: dpsgd_net
mode: from_scratch

gpus: [0]
num_workers: 3

num_epochs: 100
warmup_steps: 500
batch_size: 512
lr: 0.1
momentum: 0.9
wd: 1e-4

dp: True
augment: False
sigma: 1.5
c: 10
delta: 1e-5