dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights
relpath_ckpt: ckpt_ylzou/cifar100_opacus_net_from_scratch_epoch100_bs512_lr0.1/last.ckpt
relpath_predict: ckpt_ylzou/cifar100_opacus_net_from_scratch_epoch100_bs512_lr0.1/last

dataset: cifar100
net: opacus_net
mode: from_scratch
optimizer: sgd

gpus: [0, 1]
num_workers: 4

num_epochs: 90
warmup_steps: 50
batch_size: 2000
lr: 0.1
momentum: 0.9
wd: 0

dp: True
augment: False
sigma: 1.5
c: 10
delta: 1e-5

attacker: black_box
