dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar100
net: resnet
adapter: bottleneck_adapter
#mode: from_scratch
mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: adamw
attacker: black_box
weight: pretrain

gpus: [0, 1, 2, 3, 4, 5, 6, 7]
num_workers: 4


num_epochs: 50
warmup_steps: 500
batch_size: 1024
max_batch_size: 64
num_views: 3
# lr setting:
# non-dp: for 'fine_tuning'
# dp: 7e-4 for 'fine_tuning', 5e-3 for 'linear_probing', for 'adapter', for 'from_scratch'
lr: 1e-4
momentum: 0.9
wd: 0.0

dp: True
augment: True
#sigma: 1.5
#c: 10
c: 1
delta: 1e-5
epsilon: 8
