dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: cifar100
net: vit
adapter: mlp_adapter
#mode: from_scratch
#mode: fine_tuning
#mode: linear_probing
mode: adapter

gpus: [1]
num_workers: 8

# 100 for 'from_scratch', 50 for others
num_epochs: 50
warmup_steps: 100
batch_size: 512
# lr setting:
# non-dp: 3e-3 for 'fine_tuning' and 'adapter', 1e-2 for 'linear_probing', 1e-1 for 'from_scratch'
# dp: 3e-3 for 'adapter', 'linear_probing', and 'from_scratch', 1e-3 for 'fine_tuning'
lr: 3e-3
momentum: 0.9
wd: 1e-4

dp: False
augment: False
sigma: 1.5
c: 10
delta: 1e-5
