dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: ucf101
net: mvit
adapter: video_mlp_adapter
#mode: from_scratch
mode: fine_tuning
#mode: linear_probing
#mode: adapter
optimizer: adamw
weight: pretrain

gpus: [0,1,2,3,4,5,6,7]
num_workers: 4

num_epochs: 30
warmup_steps: 500
batch_size: 64
lr:
  sgd: 3e-4
  adamw: 4e-4
  sgd_dp: 3e-4
  adamw_dp: 1e-3
momentum: 0.9
wd:
  sgd: 1e-4
  adamw: 1e-2

T: 16
tau: 4
fps: 30

dp: True
augment: False
sigma: 0.5
c: 0.5
delta: 1e-5
