dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: ucf101
net: mvit
adapter: video_mlp_adapter
#mode: fine_tuning
#mode: linear_probing
mode: adapter

gpus: [0]
num_workers: 4

num_epochs: 30
warmup_steps: 500
batch_size: 16
lr: 3e-2
momentum: 0.9
wd: 1e-4

T: 16
tau: 4
fps: 30

dp: False
augment: True
sigma: 1.5
c: 10
delta: 1e-5
