dir_data: /home/ssd/data
dir_log: /home/ssd/log
dir_weights: /home/ssd/weights

dataset: ucf101
net: mvit
adapter: video_mlp_adapter
#mode: from_scratch
mode: fine_tuning
#mode: linear_probing
#mode: adapter

gpus: [0,1,2,3,4,5,6,7]
num_workers: 4

num_epochs: 30
warmup_steps: 50
batch_size: 64
lr: 3e-4
momentum: 0.9
wd: 1e-4

T: 16
tau: 4
fps: 30

dp: True
augment: False
sigma: 1.5
c: 10
delta: 1e-5
